### PR TITLE
Create ITraceLogger interface

### PR DESCRIPTION
**Pull request by profix898**
Related to #23, here is a PR that refactors (trace)logger usage to
1. allow custom logger implementations
2. remove ASCOM.Tools (with Sofa library and hard-coded logger) depdency in Alpaca/Com packages

_Note: When I removed unused usings after refactoring, I noticed a lot of unused using statements that are not related to my changes. They are still part of this PR. If you want me to exclude those changes let me know. I suspect that they are orphaned code from earlier work._

### CODE REVIEW

**Comment by DanielVanNoord** [comment]
I would rather not add another logger interface when ILogger (https://github.com/ASCOMInitiative/ASCOMLibrary/blob/master/ASCOM.Common/ASCOM.Common.Interfaces/ILogger.cs) already exists but we should see what the other maintainers think. As Peter mentioned in the issue I would recommend posting a proposal for changes like this in the library specific group before making them. I just sent an invite to the email associated with your git commits.

My other concern is that this has a lot of noise in the changes, looks like 51 files have been changed including more then 2000 lines in ImageArrayTests (probably an auto-formatter was run?). Most of this looks like white space and other cleanup but it makes a change like this much harder to review.

**Comment by profix898** [comment]
Thanks for your comments.

1. I opened the related issue exactly for the reason of discussing this! It is absolutely not obvious to someone on Github that you do all discussions on a separate channel ...
2. I'm perfectly fine with discussing the general direction my changes are taking. I think I described my motivation and goals clearly in the related issue.
3. As I mentioned in my note above, I'm happy to remove any non-specific changes (ImageArrayTests was an overside on my part, sorry).
4. If you dont want changes of that sort, I'm happy to run with a personal fork of the repo. But I had the impression that you are looking for feedback.

**Comment by DanielVanNoord** [comment]
We are looking for feedback and improvements. My primary point (and I am only one maintainer so others may have a different opinion) was that if we are going to refactor Alpaca and COM to use a logging interface (which I think is a better design then the current design) I would rather use the existing ILogger than add another logging interface. This is mostly a preference to avoid having two separate logging interfaces in the same project.
I had thought that Peter had already invited you in the reference issue to discuss your proposed changes, my apologies. Some of the people who test and use these libraries don't follow the GitHub repo so we often (but not always) discuss changes there first.
Thank you for your pull request, I hope that my feedback was not seen as overly negative. My comment was mostly addressed to Peter and the others who are going to review / advise changes. Looking through this it overall seems like an improvement.

**Comment by profix898** [comment]
@DanielVanNoord: If you dont like the _ITraceLogger_ approach with an additional interface, there are two options from my POV:
1. Combine _ILogger_ and _ITraceLogger_ into a single _ILogger_ interface.
2. Keep _ILogger_ only and write a helper method (probably as extension method to ILogger) that formats a component-specific (ITraceLogger) message and logs it to an _ILogger_ instance.
3. As a third option, we could remove the custom _ILogger_ and go with MS's ILogger (Microsoft.Extensions.Logging.Abstractions), which is used by many mainstream components in the .NET universe these days.

As a sidenote: I have been involved in open projects for many years, and essentially all of them have additional channels for (realtime) discussion (e.g. Discord, etc.). However, all of them use the issue tracker on their respective platform for issues and code review. I guess what I'm saying is: In other projects the additional channel is optional, for you it seems to be the primary feed for discussion. I didn't realize that until now.

**Review by Peter-Simpson — COMMENTED** [review]
Hi Thilo,

Thanks for pointing out the dependencies on Ascom.Tools, by the Alpaca Components and the COM Components projects. We agreed some time ago that we would only use the ILogger interface within the Library, and the issues you found are due to associated changes not being fully completed... and then forgotten!

The Alpaca clients had already been converted to log messages using the ILogger.Log method but I had not changed the logging class type from TraceLogger to ILogger. I've just done this and the dependency on Ascom.Tools is now gone from the Alpaca Clients.

A similar situation existed in the COM Components except that I had made neither the logger type change nor the conversion to use the ILogger.Log method. I've now made these changes and the COM Component dependency on ASCOM.Tools is also gone. I had to add a new method to the static PlatformUtilities class that will accept an ILogger instance, but this is a small price to pay for removing the dependency.

I think this approach meets your requirement and is in line with the logging technical policy that we established for the Library, I am rather concerned about the using statements that are no longer present in your pull request, so I suggest that we don't approve it and that you check out beta 10 that I'll post shortly.

Best wishes, Peter

**Comment by Peter-Simpson** [comment]
> I think that there is also an option 4 (which is similar to option 2) which is to change the existing library calls to TraceLogger to match the existing ILogger interface but I would like to hear @Peter-Simpson thoughts on these proposed changes first.

Hi Daniel, I've just done exactly that. It keeps it clean per our agreement only to use ILogger within the Library. I'm just about the post beta 10.

Best wishes, Peter

**Comment by profix898** [comment]
Hi Peter,

I'm perfectly fine with everything you just mentioned. I didn't know that you already considered (and forgot about) a more consistent ILogger usage throughout the library, which would remove the ASCOM.Tools dependency. I'm sorry to cause so much confusion, but from my POV it is absolutely worth it, with all the changes you made resulting from my comments ;) Great work. Thanks a lot!

Closing PR following your changes.

Cheers
Thilo

P.S. I just joined the net6lib group and will read/write/discuss more there if needed.

**Comment by profix898** [comment]
BTW: The proper versioning scheme would be '1.0.0-beta10' (or even '1.0.0-beta.10' for full semver 2 compatibility).

See https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/versioning
or
https://devblogs.microsoft.com/nuget/supporting-semver-2-0-0/

**Comment by Peter-Simpson** [comment]
I did load the Alpaca components package as version 1.0.0-beta10 https://www.nuget.org/packages/ASCOM.Alpaca.Components/1.0.0-beta10 but NuGet said that this was earlier than 1.0.0.beta9 and placed it just after 1.0.0beta1. Any idea why it did this?

**Comment by profix898** [comment]
Because you were missing the dash-separated suffix. By convention pre-release packages are denoted with '-betaX'. NuGet assumes packages without a trailing dash component to be stable.

See https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/concepts/Package-Versioning.md

I guess you have to unpublish earlier packages (with malformed version specifier) for pre-release beta10 to take precedence.

**Comment by profix898** [comment]
I just looked on nuget.org. You have 1.0.1-beta1 and 1.0.0-beta10. Which one is supposed to be the latest version?

**Comment by Peter-Simpson** [comment]
Yes, 1.0.0.beta9 was a typo. 

When I uploaded 1.0.0-beta10, NuGet said that there was a later version and put 1.0.0-beta10 just above 1.0.0-beta1. It looks like NuGet isn't treating the beta version number as a number but as text; with hindsight I guess that's reasonable.

Version 1.0.1-beta1 is the latest version.

**Pull request closed without merging**
